### PR TITLE
Revert "Add additional paging methods"

### PR DESCRIPTION
**Pull request by polothy**
Reverts wbrefvem/go-bitbucket#7

Very sorry if this was not clear, but this should only have been merged if https://github.com/wbrefvem/go-bitbucket/pull/6 was _not_ merged.  I made both so you could choose which you wanted to use (since we are working asynchronously).

https://github.com/wbrefvem/go-bitbucket/pull/6 is more comprehensive, so if you liked that then let's stick with it.

### CODE REVIEW

**Comment by polothy** [comment]
Thanks for merging https://github.com/wbrefvem/go-bitbucket/pull/6 - I think for the medium term, it's nice because it adds paging for everything.

**Comment by polothy** [comment]
@wbrefvem friendly reminder - think the package is broken without reverting this

**Comment by polothy** [comment]
@wbrefvem Sorry if you are on vacation (if so, please ignore until after!!!), but would like to wrap up this fix for JX.  Right now, in master if you try to build you get this:
```
❯ go build -v ./
github.com/wbrefvem/go-bitbucket/vendor/golang.org/x/net/context
github.com/wbrefvem/go-bitbucket/vendor/golang.org/x/oauth2/internal
github.com/wbrefvem/go-bitbucket/vendor/golang.org/x/oauth2
github.com/wbrefvem/go-bitbucket
# github.com/wbrefvem/go-bitbucket
./commitstatuses_api.go:367:39: a.client.PageGet undefined (type *APIClient has no field or method PageGet)
./issue_tracker_api.go:268:39: a.client.PageGet undefined (type *APIClient has no field or method PageGet)
./teams_api.go:117:39: a.client.PageGet undefined (type *APIClient has no field or method PageGet)
```

If you merge this PR, then the build works fine.  I made the mistake of sending 2 conflicting PRs on the condition that only 1 should be merged.  This fixes that in favor of #6.

**Comment by wbrefvem** [comment]
@polothy Thanks for the ping, I haven't been able to look at this in awhile.

**Comment by polothy** [comment]
Thanks so much!  Really appreciated!

**Pull request merged**
